// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvqB125nOe467T3o0lJAM8ggCJRz8YLe4',
    appId: '1:126252788444:web:1b53bdd2077f0e85fae219',
    messagingSenderId: '126252788444',
    projectId: 'ever-quid',
    authDomain: 'ever-quid.firebaseapp.com',
    databaseURL: 'https://ever-quid-default-rtdb.firebaseio.com',
    storageBucket: 'ever-quid.firebasestorage.app',
    measurementId: 'G-PGJY36L6CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7QtF9EUbVs_5mVFxZWS-NdzYwV9dbU0',
    appId: '1:126252788444:android:881831d4d119dd40fae219',
    messagingSenderId: '126252788444',
    projectId: 'ever-quid',
    databaseURL: 'https://ever-quid-default-rtdb.firebaseio.com',
    storageBucket: 'ever-quid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ119ASVVbDKv2oqVtWsVTJWFsLer7tqQ',
    appId: '1:126252788444:ios:ff2ad7369dee0cccfae219',
    messagingSenderId: '126252788444',
    projectId: 'ever-quid',
    databaseURL: 'https://ever-quid-default-rtdb.firebaseio.com',
    storageBucket: 'ever-quid.firebasestorage.app',
    iosClientId: '126252788444-ksvnlv29e235t0nn47ct8obr0opnvbhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ119ASVVbDKv2oqVtWsVTJWFsLer7tqQ',
    appId: '1:126252788444:ios:ff2ad7369dee0cccfae219',
    messagingSenderId: '126252788444',
    projectId: 'ever-quid',
    databaseURL: 'https://ever-quid-default-rtdb.firebaseio.com',
    storageBucket: 'ever-quid.firebasestorage.app',
    iosClientId: '126252788444-ksvnlv29e235t0nn47ct8obr0opnvbhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dating',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvqB125nOe467T3o0lJAM8ggCJRz8YLe4',
    appId: '1:126252788444:web:928d09b4452c1a5cfae219',
    messagingSenderId: '126252788444',
    projectId: 'ever-quid',
    authDomain: 'ever-quid.firebaseapp.com',
    databaseURL: 'https://ever-quid-default-rtdb.firebaseio.com',
    storageBucket: 'ever-quid.firebasestorage.app',
    measurementId: 'G-0DZS84DBKJ',
  );
}
